### PR TITLE
Game config support

### PR DESCRIPTION
**Pull request by zer0k-z**
- Add gamedata config support
- Move some virtual functions to use offsets instead of vtable to be consistent, 
- Revamp utils/KZUtils class
- Try to avoid CALL_VIRTUAL in implementation code if possible
- Fix broken noclip
- Add serverGlobals snapshot, rename GetGlobals utils functions
- Add OnPhysicsSimulate hook for 128t, revamp ckz angle interpolation
- Fix ladder teleport
- Fix jumpstats being broken with network spikes/timescale
- Cleanup `{};`
- Move water fix to mode manager
- Update CMoveData

### CODE REVIEW

**Comment by himenekocn** [comment]
new commit Fix LJ bug? @zer0k-z

**Comment by zer0k-z** [comment]
> new commit Fix LJ bug? @zer0k-z

Not sure what bug you are talking about, if it is the one where you jump higher with a lag switch, then it's only fixed in ckz.

**Comment by himenekocn** [comment]
> > new commit Fix LJ bug? @zer0k-z
> 
> Not sure what bug you are talking about, if it is the one where you jump higher with a lag switch, then it's only fixed in ckz.

My server player said they lose speed as soon as they turn direction, i dont know why, i just sync your update.

**Comment by himenekocn** [comment]
> > new commit Fix LJ bug? @zer0k-z
> 
> Not sure what bug you are talking about, if it is the one where you jump higher with a lag switch, then it's only fixed in ckz.

I will try the latest version tomorrow.

**Pull request merged**
