### PR TITLE
Add more commands

### PR DESCRIPTION
**Pull request by himenekocn**

### CODE REVIEW

**Comment by himenekocn** [comment]
@zer0k-z Added some short commands and tips

**Comment by zer0k-z** [comment]
Can you send a PR to the `gameconfig` branch instead of this branch? We're switching to gamedata files soon and addresses.h will soon be deprecated.

**Comment by himenekocn** [comment]
> Can you send a PR to the `gameconfig` branch instead of this branch? We're switching to gamedata files soon and addresses.h will soon be deprecated.

ok

**Comment by himenekocn** [comment]
> Can you send a PR to the branch instead of this branch? We're switching to gamedata files soon and addresses.h will soon be deprecated.`gameconfig`

how to delete these commit.

**Comment by zer0k-z** [comment]
You can do `git reset --hard HEAD~X` (X is number of commits to go backwards) and `git push --force` onto the branch.

**Comment by himenekocn** [comment]
> You can do `git reset --hard HEAD~X` (X is number of commits to go backwards) and `git push --force` onto the branch.

i'm reset now

**Pull request merged**
